# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# level_1 = CarCategory.where(depth: 1, state: '使用')
#
# level_3 = CarCategory.where(depth: 1, state: '使用')

CarCategory.find(1).update!(translate_name: "audi")
CarCategory.find(2).update!(translate_name: "aston martin")
CarCategory.find(3).update!(translate_name: "alfa romeo")
CarCategory.find(4).update!(translate_name: "AC Schnitzer")
CarCategory.find(5).update!(translate_name: "Artega")
CarCategory.find(6).update!(translate_name: "奥克斯")
CarCategory.find(7).update!(translate_name: "honda")
CarCategory.find(8).update!(translate_name: "buick")
CarCategory.find(9).update!(translate_name: "mercedes")
CarCategory.find(10).update!(translate_name: "bmw")
CarCategory.find(11).update!(translate_name: "比亚迪")
CarCategory.find(12).update!(translate_name: "宝骏")
CarCategory.find(13).update!(translate_name: "peugeot")
CarCategory.find(14).update!(translate_name: "北汽幻速")
CarCategory.find(15).update!(translate_name: "porsche")
CarCategory.find(16).update!(translate_name: "北汽绅宝")
CarCategory.find(17).update!(translate_name: "奔腾")
CarCategory.find(18).update!(translate_name: "北京")
CarCategory.find(19).update!(translate_name: "北汽威旺")
CarCategory.find(20).update!(translate_name: "北汽制造")
CarCategory.find(21).update!(translate_name: "bentley")
CarCategory.find(22).update!(translate_name: "Bugatti")
CarCategory.find(23).update!(translate_name: "brabus")
CarCategory.find(24).update!(translate_name: "BORGWARD")
CarCategory.find(25).update!(translate_name: "北汽新能源")
CarCategory.find(26).update!(translate_name: "保斐利")
CarCategory.find(27).update!(translate_name: "宝龙")
CarCategory.find(28).update!(translate_name: "长安汽车")
CarCategory.find(29).update!(translate_name: "长安欧尚")
CarCategory.find(30).update!(translate_name: "长城 ")
CarCategory.find(31).update!(translate_name: "昌河")
CarCategory.find(32).update!(translate_name: "长安跨越")
CarCategory.find(33).update!(translate_name: "长城华冠")
CarCategory.find(34).update!(translate_name: "成功")
CarCategory.find(35).update!(translate_name: "长久汽车")
CarCategory.find(36).update!(translate_name: "volkswagen")
CarCategory.find(37).update!(translate_name: "东风风行")
CarCategory.find(38).update!(translate_name: "东风风神")
CarCategory.find(39).update!(translate_name: "东南")
CarCategory.find(40).update!(translate_name: "东风风光")
CarCategory.find(41).update!(translate_name: "dodge")
CarCategory.find(42).update!(translate_name: "DS")
CarCategory.find(43).update!(translate_name: "东风小康")
CarCategory.find(44).update!(translate_name: "东风·郑州日产")
CarCategory.find(45).update!(translate_name: "东风御风")
CarCategory.find(46).update!(translate_name: "东风风度")
CarCategory.find(47).update!(translate_name: "东风")
CarCategory.find(48).update!(translate_name: "底特律电动车")
CarCategory.find(49).update!(translate_name: "Daewoo")
CarCategory.find(50).update!(translate_name: "大迪")
CarCategory.find(51).update!(translate_name: "toyota")
CarCategory.find(52).update!(translate_name: "ford")
CarCategory.find(53).update!(translate_name: "福田")
CarCategory.find(54).update!(translate_name: "ferrari")
CarCategory.find(55).update!(translate_name: "fiat")
CarCategory.find(56).update!(translate_name: "福迪")
CarCategory.find(57).update!(translate_name: "福汽启腾")
CarCategory.find(58).update!(translate_name: "飞驰商务车")
CarCategory.find(59).update!(translate_name: "Faralli Mazzanti")
CarCategory.find(60).update!(translate_name: "Fisker")
CarCategory.find(61).update!(translate_name: "富奇")
CarCategory.find(62).update!(translate_name: "福达")
CarCategory.find(63).update!(translate_name: "trumpchi")
CarCategory.find(64).update!(translate_name: "qoros")
CarCategory.find(65).update!(translate_name: "广汽吉奥")
CarCategory.find(66).update!(translate_name: "GMC")
CarCategory.find(67).update!(translate_name: "广汽中兴")
CarCategory.find(68).update!(translate_name: "Mitsuoka")
CarCategory.find(69).update!(translate_name: "GTA")
CarCategory.find(70).update!(translate_name: "广汽日野")
CarCategory.find(71).update!(translate_name: "haval")
CarCategory.find(72).update!(translate_name: "海马")
CarCategory.find(73).update!(translate_name: "hongqi")
CarCategory.find(74).update!(translate_name: "华泰")
CarCategory.find(75).update!(translate_name: "Hummer")
CarCategory.find(76).update!(translate_name: "黄海")
CarCategory.find(77).update!(translate_name: "哈飞")
CarCategory.find(78).update!(translate_name: "海马商用车")
CarCategory.find(79).update!(translate_name: "华颂")
CarCategory.find(80).update!(translate_name: "华泰新能源")
CarCategory.find(81).update!(translate_name: "海格")
CarCategory.find(82).update!(translate_name: "汇众")
CarCategory.find(83).update!(translate_name: "华普")
CarCategory.find(84).update!(translate_name: "恒天汽车")
CarCategory.find(85).update!(translate_name: "黑豹")
CarCategory.find(86).update!(translate_name: "汉江")
CarCategory.find(87).update!(translate_name: "航天圆通")
CarCategory.find(88).update!(translate_name: "华阳")
CarCategory.find(89).update!(translate_name: "geely")
CarCategory.find(90).update!(translate_name: "江淮")
CarCategory.find(91).update!(translate_name: "Jeep")
CarCategory.find(92).update!(translate_name: "jaguar")
CarCategory.find(93).update!(translate_name: "江铃")
CarCategory.find(94).update!(translate_name: "金杯")
CarCategory.find(95).update!(translate_name: "金龙")
CarCategory.find(96).update!(translate_name: "九龙")
CarCategory.find(97).update!(translate_name: "江铃集团轻汽")
CarCategory.find(98).update!(translate_name: "金旅客车")
CarCategory.find(99).update!(translate_name: "江南")
CarCategory.find(100).update!(translate_name: "金程")
CarCategory.find(101).update!(translate_name: "吉林江北")
CarCategory.find(102).update!(translate_name: "cadillac")
CarCategory.find(103).update!(translate_name: "开瑞")
CarCategory.find(104).update!(translate_name: "chrysler")
CarCategory.find(105).update!(translate_name: "凯翼")
CarCategory.find(106).update!(translate_name: "卡威")
CarCategory.find(107).update!(translate_name: "Koenigsegg")
CarCategory.find(108).update!(translate_name: "科瑞斯的")
CarCategory.find(109).update!(translate_name: "康迪全球鹰电动汽车")
CarCategory.find(110).update!(translate_name: "kaersen")
CarCategory.find(111).update!(translate_name: "KTM")
CarCategory.find(112).update!(translate_name: "陆风")
CarCategory.find(113).update!(translate_name: "suzuki")
CarCategory.find(114).update!(translate_name: "land rover|range rover")
CarCategory.find(115).update!(translate_name: "lexus")
CarCategory.find(33752).update!(translate_name: "C-HR")
CarCategory.find(116).update!(translate_name: "猎豹汽车")
CarCategory.find(117).update!(translate_name: "renault")
CarCategory.find(118).update!(translate_name: "lincoln")
CarCategory.find(119).update!(translate_name: "Lamborghini")
CarCategory.find(120).update!(translate_name: "力帆")
CarCategory.find(121).update!(translate_name: "rolls-royce")
CarCategory.find(122).update!(translate_name: "莲花")
CarCategory.find(123).update!(translate_name: "蓝海房车")
CarCategory.find(124).update!(translate_name: "Lotus")
CarCategory.find(125).update!(translate_name: "理念")
CarCategory.find(126).update!(translate_name: "雷丁电动")
CarCategory.find(127).update!(translate_name: "陆地方舟")
CarCategory.find(128).update!(translate_name: "领志")
CarCategory.find(129).update!(translate_name: "朗世")
CarCategory.find(130).update!(translate_name: "Rover")
CarCategory.find(131).update!(translate_name: "mazda")
CarCategory.find(132).update!(translate_name: "MG")
CarCategory.find(133).update!(translate_name: "maserati")
CarCategory.find(134).update!(translate_name: "MINI")
CarCategory.find(135).update!(translate_name: "mclaren")
CarCategory.find(136).update!(translate_name: "Maybach")
CarCategory.find(137).update!(translate_name: "morgan")
CarCategory.find(138).update!(translate_name: "美亚")
CarCategory.find(139).update!(translate_name: "Luxgen")
CarCategory.find(140).update!(translate_name: "Noble")
CarCategory.find(141).update!(translate_name: "acura")
CarCategory.find(142).update!(translate_name: "欧朗")
CarCategory.find(143).update!(translate_name: "opel")
CarCategory.find(144).update!(translate_name: "欧联")
CarCategory.find(145).update!(translate_name: "Pagani")
CarCategory.find(146).update!(translate_name: "Peterbilt")
CarCategory.find(147).update!(translate_name: "PGO")
CarCategory.find(148).update!(translate_name: "Pontiac")
CarCategory.find(149).update!(translate_name: "kia")
CarCategory.find(150).update!(translate_name: "奇瑞")
CarCategory.find(151).update!(translate_name: "启辰")
CarCategory.find(152).update!(translate_name: "庆铃")
CarCategory.find(153).update!(translate_name: "乔治·巴顿")
CarCategory.find(154).update!(translate_name: "nissan")
CarCategory.find(155).update!(translate_name: "roewe")
CarCategory.find(156).update!(translate_name: "瑞麒")
CarCategory.find(157).update!(translate_name: "skoda")
CarCategory.find(158).update!(translate_name: "mitsubishi")
CarCategory.find(159).update!(translate_name: "subaru")
CarCategory.find(160).update!(translate_name: "上汽大通")
CarCategory.find(161).update!(translate_name: "ssangyong")
CarCategory.find(162).update!(translate_name: "smart")
CarCategory.find(163).update!(translate_name: "山姆")
CarCategory.find(164).update!(translate_name: "STARTECH")
CarCategory.find(165).update!(translate_name: "SALEEN")
CarCategory.find(166).update!(translate_name: "世爵")
CarCategory.find(167).update!(translate_name: "双环")
CarCategory.find(168).update!(translate_name: "saab")
CarCategory.find(169).update!(translate_name: "陕汽通家")
CarCategory.find(170).update!(translate_name: "三星")
CarCategory.find(171).update!(translate_name: "上雌惮S")
CarCategory.find(172).update!(translate_name: "顺旅")
CarCategory.find(173).update!(translate_name: "tesla")
CarCategory.find(174).update!(translate_name: "泰卡特")
CarCategory.find(175).update!(translate_name: "腾势")
CarCategory.find(176).update!(translate_name: "天马")
CarCategory.find(177).update!(translate_name: "通田")
CarCategory.find(178).update!(translate_name: "塔菲克")
CarCategory.find(179).update!(translate_name: "五菱")
CarCategory.find(180).update!(translate_name: "volvo")
CarCategory.find(181).update!(translate_name: "isuzu")
CarCategory.find(182).update!(translate_name: "潍柴英致")
CarCategory.find(183).update!(translate_name: "威麟")
CarCategory.find(184).update!(translate_name: "Wiesmann")
CarCategory.find(185).update!(translate_name: "潍柴欧睿")
CarCategory.find(186).update!(translate_name: "万丰")
CarCategory.find(187).update!(translate_name: "hyundai")
CarCategory.find(188).update!(translate_name: "Chevrolet")
CarCategory.find(189).update!(translate_name: "citroen")
CarCategory.find(190).update!(translate_name: "星客特")
CarCategory.find(191).update!(translate_name: "新凯")
CarCategory.find(192).update!(translate_name: "Seat")
CarCategory.find(193).update!(translate_name: "新雅途")
CarCategory.find(194).update!(translate_name: "新大地")
CarCategory.find(195).update!(translate_name: "Infiniti")
CarCategory.find(196).update!(translate_name: "一汽")
CarCategory.find(197).update!(translate_name: "野马汽车")
CarCategory.find(198).update!(translate_name: "iveco")
CarCategory.find(199).update!(translate_name: "永源")
CarCategory.find(200).update!(translate_name: "宇通")
CarCategory.find(201).update!(translate_name: "御捷")
CarCategory.find(202).update!(translate_name: "游侠汽车")
CarCategory.find(203).update!(translate_name: "云豹")
CarCategory.find(204).update!(translate_name: "扬州亚星客车")
CarCategory.find(205).update!(translate_name: "云雀")
CarCategory.find(206).update!(translate_name: "仪征")
CarCategory.find(207).update!(translate_name: "友谊客车")
CarCategory.find(208).update!(translate_name: "众泰")
CarCategory.find(209).update!(translate_name: "中华")
CarCategory.find(210).update!(translate_name: "知豆")
CarCategory.find(211).update!(translate_name: "中兴")
CarCategory.find(212).update!(translate_name: "中欧奔驰房车")
CarCategory.find(213).update!(translate_name: "浙江卡尔森")
CarCategory.find(214).update!(translate_name: "重汽王牌")
CarCategory.find(215).update!(translate_name: "之诺")
CarCategory.find(216).update!(translate_name: "中通客车")
CarCategory.find(217).update!(translate_name: "中顺")
CarCategory.find(218).update!(translate_name: "中客华北")
CarCategory.find(33690).update!(translate_name: "阿尔特")
CarCategory.find(33691).update!(translate_name: "比速汽车")
CarCategory.find(33692).update!(translate_name: "北汽瑞丽")
CarCategory.find(33693).update!(translate_name: "东风风诺")
CarCategory.find(33694).update!(translate_name: "汉腾")
CarCategory.find(33695).update!(translate_name: "华凯")
CarCategory.find(33696).update!(translate_name: "LeSEE")
CarCategory.find(33697).update!(translate_name: "SWM斯威汽车")
CarCategory.find(33698).update!(translate_name: "WEY")
CarCategory.find(33699).update!(translate_name: "蔚来")
CarCategory.find(33700).update!(translate_name: "小鹏汽车")
CarCategory.find(33701).update!(translate_name: "驭胜")
CarCategory.find(33702).update!(translate_name: "雅宾纳")
CarCategory.find(37312).update!(translate_name: "Faraday Future")
CarCategory.find(37313).update!(translate_name: "LYNK&CO")


level_1 = CarCategory.available_depth_1
level_3 = CarCategory.available_depth_3
level_1.each do |c|
  if c.translate_name.strip != c.name.strip
    c.update!(keyword: c.name.strip + "|" + c.translate_name.strip)
  else
    c.update!(keyword: c.name.strip)
  end
  c.update!(fullname: c.name.strip)
end

level_3.each do |car|
  car.update!(name: car.name.gsub("宝马", "")) if car.name.include?("宝马")
  car.update!(name: car.name.gsub("系", " series ")) if (car.name.include?("系") && car.parent_id == CarCategory.find_by(translate_name: "bmw").id.to_s)
  car.update!(name: car.name.gsub("级", " class ")) if (car.name.include?("级") && car.parent_id == CarCategory.find_by(translate_name: "mercedes").id.to_s)
  car.update!(name: car.name.gsub("级", " class ")) if (car.name.include?("级") && car.parent_id == CarCategory.find_by(translate_name: "brabus").id.to_s)
  car.update!(name: car.name.gsub("两厢", "hatchback")) if car.name.include?("两厢")
  car.update!(name: car.name.gsub("三厢", "sedan")) if car.name.include?("三厢")
  car.update!(name: car.name.gsub("传祺", "")) if car.name.include?("传祺")
  car.update!(name: car.name.gsub("(进口)", "")) if car.name.include?("(进口)")
  car.update!(fullname: car.fullname.gsub("(进口)", "")) if car.fullname.include?("(进口)")
end

# level_1.each do |b|
#   cars = level_3.where(parent_id: b.id)
#   if cars.any?
#     cars.each do |c|
#       c.update!(keyword: b.fullname + " " + c.name)
#     end
#   end
# end


#car translate
CarCategory.find_by(id:290).update!(translate_name: "greiz")
CarCategory.find_by(id:291).update!(translate_name: "jade")
CarCategory.find_by(id:292).update!(translate_name: "spirior")
CarCategory.find_by(id:293).update!(translate_name: "ciimo")
CarCategory.find_by(id:294).update!(translate_name: "civic")
CarCategory.find_by(id:33704).update!(translate_name: "gienia")
CarCategory.find_by(id:297).update!(translate_name: "odyssey")
CarCategory.find_by(id:298).update!(translate_name: "vezel")
CarCategory.find_by(id:299).update!(translate_name: "fit")
CarCategory.find_by(id:300).update!(translate_name: "CITY")
CarCategory.find_by(id:302).update!(translate_name: "crosstour")
CarCategory.find_by(id:303).update!(translate_name: "crider")
CarCategory.find_by(id:304).update!(translate_name: "accord")
CarCategory.find_by(id:33706).update!(translate_name: "avancier")
CarCategory.find_by(id:309).update!(translate_name: "insight")
CarCategory.find_by(id:310).update!(translate_name: "S660")
CarCategory.find_by(id:288).update!(translate_name: "elysion")
CarCategory.find_by(id:322).update!(translate_name: "envision")
CarCategory.find_by(id:324).update!(translate_name: "Regal")
CarCategory.find_by(id:325).update!(translate_name: "lacrosse")
CarCategory.find_by(id:326).update!(translate_name: "excelle")
CarCategory.find_by(id:327).update!(translate_name: "Park Avenue")
CarCategory.find_by(id:328).update!(translate_name: "verano_normal")
CarCategory.find_by(id:330).update!(translate_name: "excelle")
CarCategory.find_by(id:333).update!(translate_name: "excelle-hrv")
CarCategory.find_by(id:336).update!(translate_name: "sail")
CarCategory.find_by(id:338).update!(translate_name: "enclave")
CarCategory.find_by(id:348).update!(translate_name: "vito")
CarCategory.find_by(id:349).update!(translate_name: "Sprinter")
CarCategory.find_by(id:351).update!(translate_name: "Viano")
CarCategory.find_by(id:360).update!(translate_name: "E class coupe")
CarCategory.find_by(id:329).update!(translate_name: "VERANO")
CarCategory.find_by(id:392).update!(translate_name: "GLE class AMG")
CarCategory.find_by(id:403).update!(translate_name: "mayback s class")
CarCategory.find_by(id:37255).update!(translate_name: "mayback g class")
CarCategory.find_by(id:364).update!(translate_name: "GLE class")
CarCategory.find_by(id:413).update!(translate_name: "2 Series Active Tourer")
CarCategory.find_by(id:412).update!(translate_name: "2 Series Gran Tourer ")
CarCategory.find_by(id:534).update!(translate_name: "D20 ")
CarCategory.find_by(id:535).update!(translate_name: "D20 两厢")
CarCategory.find_by(id:536).update!(translate_name: "D20 三厢")
CarCategory.find_by(id:594).update!(translate_name: "G class ")
CarCategory.find_by(id:590).update!(translate_name: "VERYON")
CarCategory.find_by(id:583).update!(translate_name: "Mulsanne")
CarCategory.find_by(id:584).update!(translate_name: "Continental")
CarCategory.find_by(id:585).update!(translate_name: "Bentayga")
CarCategory.find_by(id:588).update!(translate_name: "Arnage")
CarCategory.find_by(id:595).update!(translate_name: "GL class ")
CarCategory.find_by(id:596).update!(translate_name: "ML class ")
CarCategory.find_by(id:593).update!(translate_name: "CLS class ")
CarCategory.find_by(id:582).update!(translate_name: "flying spur")
CarCategory.find_by(id:587).update!(translate_name: "Brooklands")
CarCategory.find_by(id:37323).update!(translate_name: "mayback S class ")
CarCategory.find_by(id:597).update!(translate_name: "S class ")
CarCategory.find_by(id:598).update!(translate_name: "SLK class ")
CarCategory.find_by(id:37324).update!(translate_name: "GLE class ")
CarCategory.find_by(id:599).update!(translate_name: "C class ")
CarCategory.find_by(id:720).update!(translate_name: "Lamando")
CarCategory.find_by(id:721).update!(translate_name: "Cross Lavida")
CarCategory.find_by(id:728).update!(translate_name: "Touran")
CarCategory.find_by(id:729).update!(translate_name: "Touran L")
CarCategory.find_by(id:730).update!(translate_name: "tiguan")
CarCategory.find_by(id:735).update!(translate_name: "Passat")
CarCategory.find_by(id:33739).update!(translate_name: "TERAMONT|atlas")
CarCategory.find_by(id:740).update!(translate_name: "Bora")
CarCategory.find_by(id:742).update!(translate_name: "golf")
CarCategory.find_by(id:743).update!(translate_name: "golf gti")
CarCategory.find_by(id:744).update!(translate_name: "jeta")
CarCategory.find_by(id:745).update!(translate_name: "Magotan")
CarCategory.find_by(id:746).update!(translate_name: "Sagitar")
CarCategory.find_by(id:748).update!(translate_name: "Bora hatchback")
CarCategory.find_by(id:749).update!(translate_name: "Caddy")
CarCategory.find_by(id:33740).update!(translate_name: "C-TREK")
CarCategory.find_by(id:757).update!(translate_name: "crossgolf")
CarCategory.find_by(id:760).update!(translate_name: "Beetle")
CarCategory.find_by(id:761).update!(translate_name: "Caravelle")
CarCategory.find_by(id:763).update!(translate_name: "Multivan")
CarCategory.find_by(id:764).update!(translate_name: "Scirocco")
CarCategory.find_by(id:769).update!(translate_name: "Variant")
CarCategory.find_by(id:770).update!(translate_name: "sharan")
CarCategory.find_by(id:771).update!(translate_name: "C Coupe GTE")
CarCategory.find_by(id:772).update!(translate_name: "T6")
CarCategory.find_by(id:733).update!(translate_name: "POLO")
CarCategory.find_by(id:33736).update!(translate_name: "PHIDEON")
CarCategory.find_by(id:759).update!(translate_name: "Phaeton")
CarCategory.find_by(id:823).update!(translate_name: "gam")
CarCategory.find_by(id:824).update!(translate_name: "Caliber")
CarCategory.find_by(id:825).update!(translate_name: "Journey")
CarCategory.find_by(id:826).update!(translate_name: "challenger")
CarCategory.find_by(id:915).update!(translate_name: "ez")
CarCategory.find_by(id:828).update!(translate_name: "Viper")
CarCategory.find_by(id:909).update!(translate_name: "Highlander")
CarCategory.find_by(id:910).update!(translate_name: "camary")
CarCategory.find_by(id:911).update!(translate_name: "LEVIN")
CarCategory.find_by(id:912).update!(translate_name: "LEVIN hybird")
CarCategory.find_by(id:913).update!(translate_name: "YARiS L")
CarCategory.find_by(id:914).update!(translate_name: "YARiS")
CarCategory.find_by(id:918).update!(translate_name: "CROWN")
CarCategory.find_by(id:919).update!(translate_name: "COROLLA ex")
CarCategory.find_by(id:920).update!(translate_name: "Corolla")
CarCategory.find_by(id:922).update!(translate_name: "COASTER")
CarCategory.find_by(id:923).update!(translate_name: "LAND CRUISER")
CarCategory.find_by(id:924).update!(translate_name: "PRADO")
CarCategory.find_by(id:925).update!(translate_name: "prius")
CarCategory.find_by(id:926).update!(translate_name: "rav4")
CarCategory.find_by(id:927).update!(translate_name: "REIZ")
CarCategory.find_by(id:928).update!(translate_name: "Vios")
CarCategory.find_by(id:930).update!(translate_name: "terios")
CarCategory.find_by(id:33751).update!(translate_name: "Vios fs")
CarCategory.find_by(id:932).update!(translate_name: "alphard")
CarCategory.find_by(id:933).update!(translate_name: "Fortuner")
CarCategory.find_by(id:934).update!(translate_name: "Fj CRUISER")
CarCategory.find_by(id:935).update!(translate_name: "86")
CarCategory.find_by(id:936).update!(translate_name: "sequoia")
CarCategory.find_by(id:937).update!(translate_name: "hiace")
CarCategory.find_by(id:938).update!(translate_name: "Scion tC")
CarCategory.find_by(id:939).update!(translate_name: "COASTER")
CarCategory.find_by(id:944).update!(translate_name: "Tacoma")
CarCategory.find_by(id:945).update!(translate_name: "Tundra")
CarCategory.find_by(id:947).update!(translate_name: "Venza")
CarCategory.find_by(id:948).update!(translate_name: "Mirai")
CarCategory.find_by(id:956).update!(translate_name: "HILUX")
CarCategory.find_by(id:959).update!(translate_name: "Celica")
CarCategory.find_by(id:916).update!(translate_name: "camary hybird")
CarCategory.find_by(id:965).update!(translate_name: "fiesta sedan")
CarCategory.find_by(id:963).update!(translate_name: "escort")
CarCategory.find_by(id:962).update!(translate_name: "focus")
CarCategory.find_by(id:966).update!(translate_name: "Taurus")
CarCategory.find_by(id:967).update!(translate_name: "S-MAX")
CarCategory.find_by(id:968).update!(translate_name: "edge")
CarCategory.find_by(id:969).update!(translate_name: "Mondeo")
CarCategory.find_by(id:970).update!(translate_name: "ecosport")
CarCategory.find_by(id:971).update!(translate_name: "kuga|escape")
CarCategory.find_by(id:975).update!(translate_name: "everest")
CarCategory.find_by(id:976).update!(translate_name: "Tourneo")
CarCategory.find_by(id:1416).update!(translate_name: "transit")
CarCategory.find_by(id:980).update!(translate_name: "Mustang")
CarCategory.find_by(id:981).update!(translate_name: "F150")
CarCategory.find_by(id:984).update!(translate_name: "explorer")
CarCategory.find_by(id:33755).update!(translate_name: "focus rs")
CarCategory.find_by(id:1390).update!(translate_name: "cherokee")
CarCategory.find_by(id:1391).update!(translate_name: "renegade")
CarCategory.find_by(id:33775).update!(translate_name: "Compass")
CarCategory.find_by(id:1394).update!(translate_name: "Wrangler")
CarCategory.find_by(id:1397).update!(translate_name: "patriot")
CarCategory.find_by(id:1499).update!(translate_name: "DeVille")
CarCategory.find_by(id:1503).update!(translate_name: "SLS")
CarCategory.find_by(id:1519).update!(translate_name: "Sebring")
CarCategory.find_by(id:1522).update!(translate_name: "Grand Voager")
CarCategory.find_by(id:1531).update!(translate_name: "cross fire")
CarCategory.find_by(id:1534).update!(translate_name: "PT Cruiser")
CarCategory.find_by(id:1535).update!(translate_name: "Sebring")
CarCategory.find_by(id:1571).update!(translate_name: "Alto")
CarCategory.find_by(id:1572).update!(translate_name: "S.CROSS")
CarCategory.find_by(id:1557).update!(translate_name: "GL class ")
CarCategory.find_by(id:1558).update!(translate_name: "S class ")
CarCategory.find_by(id:1586).update!(translate_name: "liana sedan")
CarCategory.find_by(id:1576).update!(translate_name: "sx4")
CarCategory.find_by(id:1578).update!(translate_name: "vitara")
CarCategory.find_by(id:1579).update!(translate_name: "Swift")
CarCategory.find_by(id:1587).update!(translate_name: "liana hatchback")
CarCategory.find_by(id:1582).update!(translate_name: "Wagon R")
CarCategory.find_by(id:1583).update!(translate_name: "x5")
CarCategory.find_by(id:1584).update!(translate_name: "LANDY")
CarCategory.find_by(id:1593).update!(translate_name: "Grand Vitara")
CarCategory.find_by(id:1594).update!(translate_name: "jimny")
CarCategory.find_by(id:1595).update!(translate_name: "KIZASHI")
CarCategory.find_by(id:1596).update!(translate_name: "Swift sport")
CarCategory.find_by(id:1597).update!(translate_name: "IGNIS")
CarCategory.find_by(id:1598).update!(translate_name: "iK-2")
CarCategory.find_by(id:33832).update!(translate_name: "Equinox")
CarCategory.find_by(id:1602).update!(translate_name: "Evoque")
CarCategory.find_by(id:1604).update!(translate_name: "discovery")
CarCategory.find_by(id:1605).update!(translate_name: "discovery sport")
CarCategory.find_by(id:1606).update!(translate_name: "rangerover")
CarCategory.find_by(id:1607).update!(translate_name: "rangerover sport")
CarCategory.find_by(id:1610).update!(translate_name: "defender")
CarCategory.find_by(id:33787).update!(translate_name: "discovery 5")
CarCategory.find_by(id:37287).update!(translate_name: "Velar")
CarCategory.find_by(id:33791).update!(translate_name: "Koleos")
CarCategory.find_by(id:1654).update!(translate_name: "Talisman")
CarCategory.find_by(id:1655).update!(translate_name: "Scenic")
CarCategory.find_by(id:1656).update!(translate_name: "Fluence")
CarCategory.find_by(id:1657).update!(translate_name: "captur")
CarCategory.find_by(id:1659).update!(translate_name: "Laguna")
CarCategory.find_by(id:1660).update!(translate_name: "megane r.s.")
CarCategory.find_by(id:1667).update!(translate_name: "Navigator")
CarCategory.find_by(id:1673).update!(translate_name: "CONTINENTAL")
CarCategory.find_by(id:1683).update!(translate_name: "Gallardo")
CarCategory.find_by(id:1652).update!(translate_name: "Kadjar")
CarCategory.find_by(id:1665).update!(translate_name: "VelSatis")
CarCategory.find_by(id:1703).update!(translate_name: "Phantom")
CarCategory.find_by(id:1704).update!(translate_name: "Wraith")
CarCategory.find_by(id:1705).update!(translate_name: "Dawn")
CarCategory.find_by(id:1788).update!(translate_name: "6sedan")
CarCategory.find_by(id:1831).update!(translate_name: "3-Wheeler")
CarCategory.find_by(id:1833).update!(translate_name: "Aero")
CarCategory.find_by(id:1834).update!(translate_name: "Aero 8")
CarCategory.find_by(id:1836).update!(translate_name: "plus 8")
CarCategory.find_by(id:1837).update!(translate_name: "Roadster")
CarCategory.find_by(id:1869).update!(translate_name: "Antara")
CarCategory.find_by(id:1870).update!(translate_name: "meriva")
CarCategory.find_by(id:1877).update!(translate_name: "astra")
CarCategory.find_by(id:1903).update!(translate_name: "RIO")
CarCategory.find_by(id:1904).update!(translate_name: "Cerato")
CarCategory.find_by(id:1905).update!(translate_name: "Sportage")
CarCategory.find_by(id:1906).update!(translate_name: "SOUL")
CarCategory.find_by(id:1907).update!(translate_name: "Sportage r")
CarCategory.find_by(id:1909).update!(translate_name: "Carnival")
CarCategory.find_by(id:1916).update!(translate_name: "Cee’d")
CarCategory.find_by(id:1917).update!(translate_name: "CARENS")
CarCategory.find_by(id:1918).update!(translate_name: "K5")
CarCategory.find_by(id:1920).update!(translate_name: "Cadenza")
CarCategory.find_by(id:1921).update!(translate_name: "Carnival")
CarCategory.find_by(id:1922).update!(translate_name: "sorento")
CarCategory.find_by(id:1923).update!(translate_name: "SHUMA")
CarCategory.find_by(id:1915).update!(translate_name: "Borrego")
CarCategory.find_by(id:1986).update!(translate_name: "Bluebird")
CarCategory.find_by(id:1987).update!(translate_name: "LIVINA")
CarCategory.find_by(id:1988).update!(translate_name: "March")
CarCategory.find_by(id:1989).update!(translate_name: "TIIDA")
CarCategory.find_by(id:1990).update!(translate_name: "X-TRAIL|rogue")
CarCategory.find_by(id:1991).update!(translate_name: "Teana")
CarCategory.find_by(id:1992).update!(translate_name: "Qashqai")
CarCategory.find_by(id:1993).update!(translate_name: "SYLPHY")
CarCategory.find_by(id:1994).update!(translate_name: "sunny")
CarCategory.find_by(id:1995).update!(translate_name: "MAXIMA")
CarCategory.find_by(id:2003).update!(translate_name: "Paladin")
CarCategory.find_by(id:37329).update!(translate_name: "Navara")
CarCategory.find_by(id:2008).update!(translate_name: "civilian")
CarCategory.find_by(id:2009).update!(translate_name: "Quest")
CarCategory.find_by(id:2011).update!(translate_name: "patrol")
CarCategory.find_by(id:2017).update!(translate_name: "Cedric")
CarCategory.find_by(id:1985).update!(translate_name: "Murano")
CarCategory.find_by(id:2014).update!(translate_name: "leaf")
CarCategory.find_by(id:2045).update!(translate_name: "FABIA")
CarCategory.find_by(id:2046).update!(translate_name: "OCTAVIA")
CarCategory.find_by(id:2047).update!(translate_name: "superb")
CarCategory.find_by(id:2048).update!(translate_name: "RAPID SPACEBACK")
CarCategory.find_by(id:2049).update!(translate_name: "RAPID SPACEBACK")
CarCategory.find_by(id:2052).update!(translate_name: "OCTAVIA rs")
CarCategory.find_by(id:33817).update!(translate_name: "KODIAQ")
CarCategory.find_by(id:2055).update!(translate_name: "Superb Derivative")
CarCategory.find_by(id:2065).update!(translate_name: "LANCER FORTIS")
CarCategory.find_by(id:2066).update!(translate_name: "Galant")
CarCategory.find_by(id:2067).update!(translate_name: "ZINGER")
CarCategory.find_by(id:2068).update!(translate_name: "LANCER")
CarCategory.find_by(id:2069).update!(translate_name: "LANCER ex")
CarCategory.find_by(id:2070).update!(translate_name: "Soveran")
CarCategory.find_by(id:2073).update!(translate_name: "outlander sport")
CarCategory.find_by(id:2074).update!(translate_name: "pajero")
CarCategory.find_by(id:33818).update!(translate_name: "outlander")
CarCategory.find_by(id:2076).update!(translate_name: "evo")
CarCategory.find_by(id:2082).update!(translate_name: "Grandis")
CarCategory.find_by(id:2088).update!(translate_name: "outback")
CarCategory.find_by(id:2089).update!(translate_name: "Tribeca")
CarCategory.find_by(id:2090).update!(translate_name: "Legacy")
CarCategory.find_by(id:2094).update!(translate_name: "forester")
CarCategory.find_by(id:2095).update!(translate_name: "Levorg")
CarCategory.find_by(id:2103).update!(translate_name: "Actyon")
CarCategory.find_by(id:2096).update!(translate_name: "impreza")
CarCategory.find_by(id:2130).update!(translate_name: "S7")
CarCategory.find_by(id:2131).update!(translate_name: "challenger")
CarCategory.find_by(id:2132).update!(translate_name: "mustang")
CarCategory.find_by(id:2133).update!(translate_name: "300s")
CarCategory.find_by(id:2134).update!(translate_name: "430s")
CarCategory.find_by(id:2129).update!(translate_name: "camaro")
CarCategory.find_by(id:33823).update!(translate_name: "S90 l")
CarCategory.find_by(id:2265).update!(translate_name: "elantra hatchback")
CarCategory.find_by(id:2238).update!(translate_name: "GT")
CarCategory.find_by(id:2251).update!(translate_name: "Elantra")
CarCategory.find_by(id:2252).update!(translate_name: "Elantra")
CarCategory.find_by(id:2253).update!(translate_name: "MISTRA")
CarCategory.find_by(id:2254).update!(translate_name: "MOINCA")
CarCategory.find_by(id:2255).update!(translate_name: "santa fe")
CarCategory.find_by(id:2256).update!(translate_name: "Tucson")
CarCategory.find_by(id:2258).update!(translate_name: "Verna")
CarCategory.find_by(id:2260).update!(translate_name: "sonata 8")
CarCategory.find_by(id:2261).update!(translate_name: "sonata 9")
CarCategory.find_by(id:2262).update!(translate_name: "Celesta")
CarCategory.find_by(id:2266).update!(translate_name: "Accent")
CarCategory.find_by(id:2272).update!(translate_name: "Genesis g90")
CarCategory.find_by(id:2278).update!(translate_name: "Rohens")
CarCategory.find_by(id:2279).update!(translate_name: "ROHENS-Coupe")
CarCategory.find_by(id:2297).update!(translate_name: "Trax")
CarCategory.find_by(id:2298).update!(translate_name: "Epica")
CarCategory.find_by(id:2311).update!(translate_name: "sail sedan")
CarCategory.find_by(id:2301).update!(translate_name: "Captiva")
CarCategory.find_by(id:2303).update!(translate_name: "malibu")
CarCategory.find_by(id:2304).update!(translate_name: "malibu xl")
CarCategory.find_by(id:2305).update!(translate_name: "sail")
CarCategory.find_by(id:2295).update!(translate_name: "aveo hatchback")
CarCategory.find_by(id:2309).update!(translate_name: "AVEO")
CarCategory.find_by(id:33828).update!(translate_name: "cavalier")
CarCategory.find_by(id:33829).update!(translate_name: "Equinox")
CarCategory.find_by(id:2315).update!(translate_name: "camaro")
CarCategory.find_by(id:2316).update!(translate_name: "volt")
CarCategory.find_by(id:2300).update!(translate_name: "Cruze hatchback")
CarCategory.find_by(id:2319).update!(translate_name: "Suburban")
CarCategory.find_by(id:2328).update!(translate_name: "c4l")
CarCategory.find_by(id:2329).update!(translate_name: "c4")
CarCategory.find_by(id:2332).update!(translate_name: "C-Quatre")
CarCategory.find_by(id:2333).update!(translate_name: "c-Elysee")
CarCategory.find_by(id:2335).update!(translate_name: "C3-XR")
CarCategory.find_by(id:2336).update!(translate_name: "fukang")
CarCategory.find_by(id:2343).update!(translate_name: "C4 PICASSO")
CarCategory.find_by(id:37299).update!(translate_name: "C5 Aircross")
CarCategory.find_by(id:37317).update!(translate_name: "01")
CarCategory.find_by(id:37318).update!(translate_name: "03")
CarCategory.find_by(id:356).update!(translate_name: "C class coupe")
CarCategory.find_by(id:1495).update!(translate_name: "ESCALADE")
CarCategory.find_by(id:1496).update!(translate_name: "ESCALADE Hybrid")
CarCategory.find_by(id:1702).update!(translate_name: "ghost")
CarCategory.find_by(id:1835).update!(translate_name: "Plus 4")
CarCategory.find_by(id:2072).update!(translate_name: "pajero sport")
CarCategory.find_by(id:723).update!(translate_name: "LAVIDA")
CarCategory.find_by(id:747).update!(translate_name: "Sportsvan")
CarCategory.find_by(id:767).update!(translate_name: "Touareg")
CarCategory.find_by(id:2314).update!(translate_name: "Corvette")
CarCategory.find_by(id:1608).update!(translate_name: "freelander2")
CarCategory.find_by(id:2239).update!(translate_name: "Roadster")
CarCategory.find_by(id:1393).update!(translate_name: "grand cherokee")
CarCategory.find_by(id:1107).update!(translate_name: "GA3S")

level_3.each do |car|
  car.update!(translate_name: car.name) if car.translate_name.nil?
end

#car keyword
level_1.each do |b|
  cars = level_3.where(parent_id: b.id)
  if cars.any?
    cars.each do |c|
      c.update!(keyword: ((c.fullname.strip.include? b.name.strip) ? c.fullname.strip : (b.name.strip + c.fullname.strip)) + "|" + b.translate_name + " " + c.translate_name)
    end
  end
end
